version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerized-laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dockerized-laravel-network
    depends_on:
      - db
  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: dockerized-laravel-webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
      # Use a single file mount instead of a directory
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dockerized-laravel-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0.21
    container_name: dockerized-laravel-db
    restart: unless-stopped
    tty: true
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - dockerized-laravel-network
    ports:
      - "3306:3306"

  # Redis for Cache and Queue
  #redis:
    #image: redis:alpine
    #container_name: dockerized-laravel-redis
    #restart: unless-stopped
    #networks:
    #  - dockerized-laravel-network
    #ports:
    #  - "6379:6379"

# Networks
networks:
  dockerized-laravel-network:
    driver: bridge

# Volumes
volumes:
  dockerized-laravel-data:
    driver: local