services:

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: zentra_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes: 
      - .:/var/www/html
      - ./dockerize/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
      - laravelzentra

  #MySQL Service
  mysql:
    image: mysql:8.0.21
    container_name: zentra_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      #MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - ./dockerize/mysql/data:/var/lib/mysql
      - ./dockerize/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - laravelzentra

  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: zentra_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - laravelzentra 

  #Composer Service
  composer:
    image: composer:latest
    container_name: zentra_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - laravelzentra    

  #NPM Service
  npm:
    image: node:22.14
    container_name: zentra_npm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"     # Vite dev server port
    command: ["npm", "run", "dev"]
    networks:
      - laravelzentra

  #Artisan Service
  artisan:
    build: 
      context: .
      dockerfile: ./dockerize/app/php.dockerfile
    container_name: zentra_artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravelzentra


#Docker Networks
networks:
  laravelzentra: